version: '3'

services:      
  iss-policy-service:
    container_name: iss-policy-service
    image: iss-policy-service
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    environment:
      - POSTGRES_HOST=postgres_db      
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
      - POSTGRES_PORT=5432     
    ports:
      - "8082:8080"
    depends_on:
      - postgres_db
      - kafka
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
    - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
    - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'      
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper      
  postgres_db:
    image: "postgres:9.6-alpine"
    container_name: postgres_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
    - "5432:5432"
    environment:
      - POSTGRES_HOST=postgres_db      
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
 
volumes:
  postgres-data: